name: deeplizard-rl

dependencies:
  - python=3.7
  - jupyterlab
  - ipywidgets
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - tqdm
  - gym
  - pyglet
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit=11.6
  - pip
  - pip:
#      - numpy
channels:
  - pytorch
  - conda-forge
  - defaults
